import os



f=os.environ.get("account_sid")
print(list(os.environ))

lst=['SHELL', 'SESSION_MANAGER', 'QT_ACCESSIBILITY', 'COLORTERM', 'XDG_CONFIG_DIRS', 'SSH_AGENT_LAUNCHER', 'XDG_MENU_PREFIX', 'TERM_PROGRAM_VERSION', 'GNOME_DESKTOP_SESSION_ID', 'LANGUAGE', 'GNOME_SHELL_SESSION_MODE', 'SSH_AUTH_SOCK', 'XMODIFIERS', 'DESKTOP_SESSION', 'GTK_MODULES', 'PWD', 'XDG_SESSION_DESKTOP', 'LOGNAME', 'XDG_SESSION_TYPE', 'SYSTEMD_EXEC_PID', 'XAUTHORITY', 'HOME', 'USERNAME', 'IM_CONFIG_PHASE', 'LANG', 'LS_COLORS', 'XDG_CURRENT_DESKTOP', 'VIRTUAL_ENV', 'VTE_VERSION', 'WAYLAND_DISPLAY', 'GNOME_TERMINAL_SCREEN', 'CHROME_DESKTOP', 'GNOME_SETUP_DISPLAY', 'LESSCLOSE', 'XDG_SESSION_CLASS', 'TERM', 'LESSOPEN', 'USER', 'GNOME_TERMINAL_SERVICE', 'DISPLAY', 'SHLVL', 'QT_IM_MODULE', 'XDG_RUNTIME_DIR', 'PS1', 'XDG_DATA_DIRS', 'GDK_BACKEND', 'PATH', 'GDMSESSION', 'ORIGINAL_XDG_CURRENT_DESKTOP', 'DBUS_SESSION_BUS_ADDRESS', 'TERM_PROGRAM', '_']